import { Inter } from "next/font/google";
import "./globals.css";
import { AuthUserProvider } from "@/firebase/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CRUD With NEXT-JS Firebase ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html  lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <AuthUserProvider>
          {children}
        </AuthUserProvider>
      </body>
    </html>
  );
}
